version: '3.8'

services:
    nginx:
        container_name: nginx
        build: nginx
        ports: 
            - 80:80
        volumes:
            - ./nginx:/etc/nginx/
        depends_on: 
            - account-api
            - auth-api

    account-api:
        build:
            context: ./account_service
            dockerfile: Dockerfile
        command: 'python manage.py runserver 0.0.0.0:8000'
        ports:
            - 8000:8000 
        volumes:
            - ./account_service:/app
        depends_on:
            - account-db

    account-db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: bank
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - .account_db_data:/var/lib/mysql
        ports: 
            - 3307:3306

    auth-api:
        build:
            context: ./authentication_service
            dockerfile: Dockerfile
        command: 'python manage.py runserver 0.0.0.0:8000'
        volumes:
            - ./authentication_service:/app
        depends_on: 
            - auth-db

    auth-db:
        image: postgres:12
        restart: always
        environment:
          POSTGRES_PASSWORD: postgres
        volumes:
            - .auth_db_data:/var/lib/postgresql/data
